<h2>आचमनं</h2>
अच्युताय नमः अनन्ताय नमः गोविन्दाय नमः
केशवा, नारयणा, <span class="note">(cheeks with thumb)</span>
माधवा, गोविन्दा, <span class="note">(eyes with ring finger)</span>
विष्णु, मधुसूदन, <span class="note">(nose with index finger)</span>
त्रिविक्रम, वामन, <span class="note">(ears with little finger)</span>
श्रीधर, ऋषीकेश, <span class="note">(shoulders with middle finger)</span>
पद्मनाभ, दमोदर । <span class="note">(navel & head with all fingers)</span>