name: Release Zip on Version Change

on:
  push:
    paths:
      - 'docs/**/version'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get changed version files
        id: changed_files
        run: |
          echo "CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'docs/.*/version' | xargs)" >> $GITHUB_ENV

      - name: Process each changed version file
        if: env.CHANGED_FILES != ''
        run: |
          for file in $CHANGED_FILES; do
            SUBFOLDER=$(dirname "$file" | sed 's|docs/||')
            VERSION=$(cat "$file" | tr -d '[:space:]')
            ZIP_NAME="${SUBFOLDER}-${VERSION}.zip"
            LATEST_ZIP_NAME="${SUBFOLDER}-latest.zip"
            echo "Processing $SUBFOLDER with version $VERSION"
            cd "docs/$SUBFOLDER"
            zip -r "../../$ZIP_NAME" ./* -x "version"
            cp "../../$ZIP_NAME" "../../$LATEST_ZIP_NAME"
            cd -
            echo "ZIP_FILES="$ZIP_FILES $ZIP_NAME $LATEST_ZIP_NAME"" >> $GITHUB_ENV
          done

      - name: Create GitHub Release
        if: env.ZIP_FILES != ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME="release-$(date +%Y%m%d-%H%M%S)"
          gh release create "$TAG_NAME" $ZIP_FILES --title "New Release" --notes "Auto-generated release from version updates."
